version: '3.1'
services:
  db:
    image: mysql:5.7
    restart: on-failure
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  wordpress-dev:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: on-failure
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: testdb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_TABLE_PREFIX: "wp_"
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG', true );
        define( 'WP_DEBUG_LOG', true );
        define( 'WP_DEBUG_DISPLAY', false );
        define( 'SCRIPT_DEBUG', true );
    volumes:
      - "./:/var/www/html/wp-content/plugins/klarna-checkout-for-woocommerce"
      - ./.wp:/var/www/html

  wordpress-cli:
    depends_on:
      - db
      - wordpress-dev
    image: wordpress:cli
    restart: on-failure
    user: xfs
    command: >
      /bin/sh -c '
      wp core install --url=http://localhost --title="Klarna Checkout" --admin_user=admin --admin_password=password --admin_email=info@example.com --path=/var/www/html --skip-email;
      wp rewrite structure /%postname%/;
      wp plugin install wordpress-importer --activate;
      wp plugin install woocommerce --activate;
      wp theme install storefront --activate;
      wp wc tool run install_pages --user=1;
      wp import wp-content/plugins/woocommerce/sample-data/sample_products.xml --authors=create;
      '
    volumes:
      - "./:/var/www/html/wp-content/plugins/klarna-checkout-for-woocommerce"
      - ./.wp:/var/www/html

volumes:
  db:
  wordpress: